### ISSUE TITLE
Module not found after npm install http-status-enum --save

### ISSUE THREAD

**Issue by kuncevic** [KyleNeedham/http-status-enum#1]
import HTTP_STATUS_CODES from 'http-status-enum';
getting error `Cant find module http-status-enum'` any thoughts?

I can see the module installed in node_modules and also have record in my `package.json`
Also tried to reinstall and restart the `vscode`.  But still getting the error.

**Comment by KyleNeedham** [comment]
I republished the v1.0.0 tag on git and NPM cached the first publish with an invalid main location in package.json. I'll push a new version tag and update NPM, which should fix everything.

**Comment by kuncevic** [comment]
Still same even with latest "name": "http-status-enum",   "version": "1.0.1" ...
`error TS2307: Cannot find module 'http-status-enum'.`

**Comment by KyleNeedham** [comment]
Hopefully the module should resolve correctly in [1.0.2](https://github.com/KyleNeedham/http-status-enum/releases/tag/1.0.2).
